apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server-deployment
  labels:
    app: ai-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      containers:
      - name: ai-server
        image: jungdae/inforest-ai-service
        ports:
        - containerPort: 8000
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        envFrom:
        - secretRef:
            name: ai-secret

---
apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
spec:
  type: ClusterIP
  selector:
    app: ai-server
  ports:
    - port: 8000
      targetPort: 8000